import yaml from 'js-yaml'

// Matches location YAML files: e.g. 001_loc_binnenhof.yaml
const LOC_FILE_PATTERN = /^\d+_loc_.*\.yaml$/
const DATA_PATH = 'src/data/text/en/projects'

async function githubRequest(path, options = {}, env) {
  const res = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}${path}`, {
    ...options,
    headers: {
      'Authorization': `Bearer ${env.GITHUB_PAT}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'freedom-hunt-editor',
      ...(options.headers ?? {}),
    },
  })
  if (!res.ok) {
    const err = await res.text()
    throw new Error(`GitHub ${res.status}: ${err}`)
  }
  return res.json()
}

export function decodeGitHubContent(base64) {
  const raw = atob(base64.replace(/\s/g, ''))
  const bytes = Uint8Array.from(raw, c => c.charCodeAt(0))
  return new TextDecoder().decode(bytes)
}

export function encodeGitHubContent(str) {
  const bytes = new TextEncoder().encode(str)
  const binary = Array.from(bytes, b => String.fromCharCode(b)).join('')
  return btoa(binary)
}

export function locationFilePath(project, city, filename) {
  return `${DATA_PATH}/${project}/${city}/${filename}`
}

export async function fetchLocations(project, city, env) {
  const files = await githubRequest(`/contents/${DATA_PATH}/${project}/${city}`, {}, env)
  const locFiles = files.filter(f => f.type === 'file' && LOC_FILE_PATTERN.test(f.name))
  return Promise.all(locFiles.map(async f => {
    const fileData = await githubRequest(`/contents/${f.path}`, {}, env)
    const content = decodeGitHubContent(fileData.content)
    const location = yaml.load(content)
    return { filename: f.name, sha: fileData.sha, location }
  }))
}

export async function fetchLocation(project, city, filename, env) {
  const fileData = await githubRequest(`/contents/${locationFilePath(project, city, filename)}`, {}, env)
  const content = decodeGitHubContent(fileData.content)
  const location = yaml.load(content)
  return { filename, sha: fileData.sha, location }
}

// Creates a branch, commits a YAML file, and opens a PR against main.
// Sequence: resolve HEAD sha → create branch → PUT file → create PR.
export async function createLocationPR(project, city, filename, yamlContent, existingSha, prTitle, env) {
  const ref = await githubRequest('/git/ref/heads/main', {}, env)
  const headSha = ref.object.sha
  const branchName = `editor/${filename.replace('.yaml', '')}-${Date.now()}`

  await githubRequest('/git/refs', {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: headSha }),
  }, env)

  const filePath = locationFilePath(project, city, filename)
  let currentSha = existingSha
  if (!currentSha) {
    try {
      const existing = await githubRequest(`/contents/${filePath}`, {}, env)
      currentSha = existing.sha
    } catch { /* file does not exist yet — no SHA needed */ }
  }

  const putBody = { message: prTitle, content: encodeGitHubContent(yamlContent), branch: branchName }
  if (currentSha) putBody.sha = currentSha
  await githubRequest(`/contents/${filePath}`, { method: 'PUT', body: JSON.stringify(putBody) }, env)

  const pr = await githubRequest('/pulls', {
    method: 'POST',
    body: JSON.stringify({
      title: prTitle,
      body: `Auto-generated by the Freedom Hunt location editor.\n\nFile: \`${filePath}\``,
      head: branchName,
      base: 'main',
    }),
  }, env)
  return { prUrl: pr.html_url, prNumber: pr.number, branchName }
}

// GitHub uses state "closed" for both merged and rejected PRs.
export async function fetchPRStatuses(numbers, env) {
  const statuses = {}
  await Promise.all(numbers.map(async n => {
    const pr = await githubRequest(`/pulls/${n}`, {}, env)
    statuses[n] = pr.state
  }))
  return statuses
}