import type { Theme, ThemeName } from "../types/theme";

export const DEFAULT_THEME: ThemeName = "app";

export const themes: Record<ThemeName, Theme> = {
  wireframe: {
    fontFamily: "Arial, sans-serif",
    background: "#ffffff",
    surface: "#f9f9f9",
    border: "#dddddd",
    text: "#111111",
    textSecondary: "#666666",
    textMuted: "#aaaaaa",
    accent: "#555555",
    barBackground: "#ffffff",
    barBorder: "#dddddd",
    barText: "#333333",
    barTextSecondary: "#888888",
    progressTrack: "#eeeeee",
    progressFill: "#555555",
    clueBackground: "transparent",
    clueBorderColor: "transparent",
  },
  app: {
    fontFamily: "'Comfortaa', sans-serif",
    background: "#0f172a",
    surface: "#1e293b",
    border: "#334155",
    text: "#f8fafc",
    textSecondary: "#94a3b8",
    textMuted: "#64748b",
    accent: "#f59e0b",
    barBackground: "#1e293b",
    barBorder: "#334155",
    barText: "#f8fafc",
    barTextSecondary: "#94a3b8",
    progressTrack: "#0f172a",
    progressFill: "#f59e0b",
    clueBackground: "#1a2744",
    clueBorderColor: "transparent",
  },
  GWC: {
    fontFamily: "'Quicksand', sans-serif",
    background: "#ffffff",
    surface: "#f0f4ff",
    border: "#e5e7eb",
    text: "#002868",
    textSecondary: "#374151",
    textMuted: "#6b7280",
    accent: "#BF0A30",
    barBackground: "#002868",
    barBorder: "#002868",
    barText: "#ffffff",
    barTextSecondary: "#93c5fd",
    progressTrack: "#001a4d",
    progressFill: "#BF0A30",
    clueBackground: "#f0f4ff",
    clueBorderColor: "#002868",
  },
};
