import yaml from 'js-yaml'

async function githubRequest(path, options = {}, env) {
  const res = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}${path}`, {
    ...options,
    headers: {
      'Authorization': `Bearer ${env.GITHUB_PAT}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'freedom-hunt-editor',
      ...(options.headers ?? {}),
    },
  })
  if (!res.ok) {
    const err = await res.text()
    throw new Error(`GitHub ${res.status}: ${err}`)
  }
  return res.json()
}

function decodeGitHubContent(base64) {
  const raw = atob(base64.replace(/\s/g, ''))
  const bytes = Uint8Array.from(raw, c => c.charCodeAt(0))
  return new TextDecoder().decode(bytes)
}

function encodeGitHubContent(str) {
  const bytes = new TextEncoder().encode(str)
  const binary = Array.from(bytes, b => String.fromCharCode(b)).join('')
  return btoa(binary)
}

async function createLocationPR(project, city, filename, yamlContent, existingSha, prTitle, env) {
  const ref = await githubRequest('/git/ref/heads/main', {}, env)
  const headSha = ref.object.sha

  const branchName = `editor/${filename.replace('.yaml', '')}-${Date.now()}`
  await githubRequest('/git/refs', {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: headSha }),
  }, env)

  const filePath = `src/data/text/en/projects/${project}/${city}/${filename}`
  let currentSha = existingSha
  if (!currentSha) {
    try {
      const existing = await githubRequest(`/contents/${filePath}`, {}, env)
      currentSha = existing.sha
    } catch {}
  }

  const putBody = {
    message: prTitle,
    content: encodeGitHubContent(yamlContent),
    branch: branchName,
  }
  if (currentSha) putBody.sha = currentSha
  await githubRequest(`/contents/${filePath}`, {
    method: 'PUT',
    body: JSON.stringify(putBody),
  }, env)

  const pr = await githubRequest('/pulls', {
    method: 'POST',
    body: JSON.stringify({
      title: prTitle,
      body: `Auto-generated by the Freedom Hunt location editor.\n\nFile: \`${filePath}\``,
      head: branchName,
      base: 'main',
    }),
  }, env)

  return { prUrl: pr.html_url, prNumber: pr.number, branchName }
}

function json(data, status = 200, headers = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...headers },
  })
}

const TOKEN_TTL_SECONDS = 30 * 24 * 60 * 60

function b64urlEncode(str) {
  return btoa(str).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '')
}

function b64urlDecode(str) {
  return atob(str.replace(/-/g, '+').replace(/_/g, '/'))
}

export async function createToken(payload, secret) {
  const encoded = b64urlEncode(JSON.stringify(payload))
  const enc = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false, ['sign']
  )
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(encoded))
  const sigB64 = b64urlEncode(String.fromCharCode(...new Uint8Array(sig)))
  return `${encoded}.${sigB64}`
}

export async function verifyToken(token, secret) {
  try {
    const dot = token.lastIndexOf('.')
    if (dot === -1) return null
    const encoded = token.slice(0, dot)
    const sigB64 = token.slice(dot + 1)
    const enc = new TextEncoder()
    const key = await crypto.subtle.importKey(
      'raw', enc.encode(secret),
      { name: 'HMAC', hash: 'SHA-256' },
      false, ['verify']
    )
    const sigBytes = Uint8Array.from(b64urlDecode(sigB64), c => c.charCodeAt(0))
    const valid = await crypto.subtle.verify('HMAC', key, sigBytes, enc.encode(encoded))
    if (!valid) return null
    const payload = JSON.parse(b64urlDecode(encoded))
    if (payload.exp < Math.floor(Date.now() / 1000)) return null
    return payload
  } catch {
    return null
  }
}

async function checkRateLimit(ip, env) {
  const key = `rl:${ip}`
  const raw = await env.AUTH_STORE.get(key)
  const now = Date.now()
  let record = raw ? JSON.parse(raw) : { count: 0, windowStart: now }
  if (now - record.windowStart > 60000) {
    record = { count: 0, windowStart: now }
  }
  record.count++
  await env.AUTH_STORE.put(key, JSON.stringify(record), { expirationTtl: 60 })
  return record.count > 5
}

async function requireAuth(request, env) {
  const cookie = request.headers.get('Cookie') || ''
  const match = cookie.match(/(?:^|;\s*)freedom_hunt_auth=([^;]+)/)
  if (!match) return null
  return verifyToken(match[1], env.AUTH_SECRET)
}

export function buildR2Key(locationId, mimeType, timestamp) {
  const ext = mimeType === 'image/png' ? 'png' : 'jpg'
  return `${locationId}_${timestamp}.${ext}`
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url)

    if (request.method === 'POST' && url.pathname === '/auth/login') {
      try {
        const clientIP = request.headers.get('CF-Connecting-IP') || 'unknown'
        const rateLimited = await checkRateLimit(clientIP, env)
        if (rateLimited) {
          return json({ ok: false, error: 'Too many attempts. Please wait a moment.' }, 429)
        }
        const { project, teamName, contact, password } = await request.json()
        if (!project || !password) {
          return json({ ok: false, error: 'Missing required fields' }, 400)
        }
        const adminPw = await env.AUTH_STORE.get(`admin:${project}`)
        const participantPw = await env.AUTH_STORE.get(`auth:${project}`)
        if (adminPw === null && participantPw === null) {
          return json({ ok: false, error: 'Project not found' }, 401)
        }
        let isAdmin = false
        if (adminPw !== null && password === adminPw) {
          isAdmin = true
        } else if (participantPw === null || password !== participantPw) {
          return json({ ok: false, error: 'Incorrect password' }, 401)
        }
        const payload = {
          project,
          teamName: teamName || '',
          contact: contact || '',
          isAdmin,
          exp: Math.floor(Date.now() / 1000) + TOKEN_TTL_SECONDS,
        }
        const token = await createToken(payload, env.AUTH_SECRET)
        return json(
          { ok: true, teamName: payload.teamName, contact: payload.contact, isAdmin },
          200,
          { 'Set-Cookie': `freedom_hunt_auth=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000` }
        )
      } catch {
        return json({ ok: false, error: 'Login failed' }, 500)
      }
    }

    if (request.method === 'GET' && url.pathname === '/auth/me') {
      const payload = await requireAuth(request, env)
      if (!payload) return json({ ok: false, error: 'Not authenticated' }, 401)
      return json({
        ok: true,
        project: payload.project,
        teamName: payload.teamName,
        contact: payload.contact,
        isAdmin: payload.isAdmin ?? false,
      })
    }

    if (request.method === 'POST' && url.pathname === '/auth/logout') {
      return json(
        { ok: true },
        200,
        { 'Set-Cookie': 'freedom_hunt_auth=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0' }
      )
    }

    if (request.method === 'POST' && url.pathname === '/upload') {
      const authPayload = await requireAuth(request, env)
      if (!authPayload) return json({ ok: false, error: 'Unauthorized' }, 401)
      try {
        const formData = await request.formData()
        const photo = formData.get('photo')
        const locationId = formData.get('locationId') || 'unknown'
        const key = buildR2Key(locationId, photo.type, Date.now())
        await env.PHOTOS.put(key, photo.stream(), {
          httpMetadata: { contentType: photo.type },
        })
        return json({ ok: true, key })
      } catch {
        return json({ ok: false, error: 'Upload failed' }, 500)
      }
    }

    if (request.method === 'POST' && url.pathname === '/form-submit') {
      const authPayload = await requireAuth(request, env)
      if (!authPayload) return json({ ok: false, error: 'Unauthorized' }, 401)
      try {
        const body = await request.text()
        const scriptRes = await fetch(env.FORM_SCRIPT_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body,
        })
        const scriptData = await scriptRes.json()
        return json({ ok: scriptData.ok ?? true })
      } catch {
        return json({ ok: false, error: 'Submission failed' }, 500)
      }
    }

    if (request.method === 'GET' && url.pathname === '/editor/locations') {
      const authPayload = await requireAuth(request, env)
      if (!authPayload?.isAdmin) return json({ ok: false, error: 'Forbidden' }, authPayload ? 403 : 401)
      const project = url.searchParams.get('project')
      const city = url.searchParams.get('city')
      if (!project || !city) return json({ ok: false, error: 'Missing project or city' }, 400)
      try {
        const dirPath = `src/data/text/en/projects/${project}/${city}`
        const files = await githubRequest(`/contents/${dirPath}`, {}, env)
        const locFiles = files.filter(f => f.type === 'file' && /^\d+_loc_.*\.yaml$/.test(f.name))
        const locations = await Promise.all(locFiles.map(async f => {
          const fileData = await githubRequest(`/contents/${f.path}`, {}, env)
          const content = decodeGitHubContent(fileData.content)
          const location = yaml.load(content)
          return { filename: f.name, sha: fileData.sha, location }
        }))
        return json({ ok: true, locations })
      } catch (err) {
        return json({ ok: false, error: err.message }, 502)
      }
    }

    if (request.method === 'GET' && url.pathname === '/editor/location') {
      const authPayload = await requireAuth(request, env)
      if (!authPayload?.isAdmin) return json({ ok: false, error: 'Forbidden' }, authPayload ? 403 : 401)
      const project = url.searchParams.get('project')
      const city = url.searchParams.get('city')
      const file = url.searchParams.get('file')
      if (!project || !city || !file) return json({ ok: false, error: 'Missing params' }, 400)
      try {
        const filePath = `src/data/text/en/projects/${project}/${city}/${file}`
        const fileData = await githubRequest(`/contents/${filePath}`, {}, env)
        const content = decodeGitHubContent(fileData.content)
        const location = yaml.load(content)
        return json({ ok: true, filename: file, sha: fileData.sha, location })
      } catch (err) {
        return json({ ok: false, error: err.message }, 502)
      }
    }

    if (request.method === 'POST' && url.pathname === '/editor/location') {
      const authPayload = await requireAuth(request, env)
      if (!authPayload?.isAdmin) return json({ ok: false, error: 'Forbidden' }, authPayload ? 403 : 401)
      try {
        const { project, city, filename, existingSha, location } = await request.json()
        if (!project || !city || !filename || !location) {
          return json({ ok: false, error: 'Missing fields' }, 400)
        }
        const yamlContent = yaml.dump(location, { lineWidth: -1, noRefs: true, indent: 2 })
        const action = location.hidden ? 'Hide' : (existingSha ? 'Edit' : 'Add')
        const prTitle = `${action} location: ${location.title || filename}`
        const result = await createLocationPR(project, city, filename, yamlContent, existingSha, prTitle, env)
        return json({ ok: true, ...result })
      } catch (err) {
        return json({ ok: false, error: err.message }, 502)
      }
    }

    if (!env.ASSETS) {
      return new Response('Not found', { status: 404 })
    }
    return env.ASSETS.fetch(request)
  },
}